### ISSUE TITLE
Issue with re-captcha on login

### ISSUE THREAD

**Issue by tameem92** [george-lim/kijiji-bot#1]
Hey, just playing around with this package, and seems like the first time I run it login failed with:

`"extensions":{"errorCode":"LOGIN_RECAPTCHA_FAIL","statusCode":401}}]`

Any ideas around that?

**Comment by Safeer-Abbas** [comment]
Hey,

I hope you found a solution to that problem, if you didnt here it is !

I got the same issue so I decided to dig in into Kiji API. They have re-captcha on there api, hence the issue LOGIN_RECAPTCHA_FAIL. You will need to use 2captcha to solve the v2 invisiable captcha and put the g-captcha response token into the payload. I am going to upload a nice and improved kiji bot on my own repository and ill if I can get the owner of this repo to accept my fix for the login function.

**Comment by Safeer-Abbas** [comment]
Got it 👍

**Comment by EdwardOak** [comment]
Recaptcha issue. 

I have checked Safeer's code but there's no read me nor comments.

Any fixes for recaptcha?

**Comment by EdwardOak** [comment]
Using 2Captcha, I get a "WRONG CAPTCHA ID" error.

**Comment by george-lim** [comment]
@Safeer-Abbas yeah if you have a solution to this problem, please make a PR! I'll test it out.

**Comment by EdwardOak** [comment]
I can vouch for him. The Captcha bypass code he wrote works, just make sure to add the according reference in the payload and make sure to "from Captcha import captcha_solver"

⁣Sent from BlueMail ​
