### ISSUE TITLE
Delay does not prevent automatic duplicate ads removal.

### ISSUE THREAD

**Issue by Gary-0ak** [george-lim/kijiji-bot#5]
No exceptions are thrown, my post-delay is a "30" which you said was default in docs.

I'm posting 6 ads, some of them make it, some of them dont.

Right now (first try of the day) 4 out of the 6 were auto-deleted. 

Question A: Should I simply go for a very long (3600) delay?
Side question: I assume the delay is in-between (remove all) and (start posting), correct? 

Question B: Is there a simple way to config repost-ads.py to make it go three-ways: delete-only/post-only/both.

Would be ideal for troubleshooting.
As of now, when an issue happens with posting, you have to wait a bit, then relaunch a full "delete/repost all", if you don't want to get firewalled/throttled (for obvious reasons). Even after waiting, probably not all ads will successfully repost.

Any idea of what part of code I should take a look at to try and create 3 different scripts like repost-ads.py, but one for each possible action (delete/post/both > both is already repost-ads.py)

**Comment by Gary-0ak** [comment]
Just tried again with 360 delay. 

Only 3 out of 6 made it.

**Comment by Gary-0ak** [comment]
Tried again with a a 3600 delay, which was not done (less than 60 seconds passed by before it started posting)

5 out of 6 made it (but I had manually deleted the 3 previous ones)

**Comment by Gary-0ak** [comment]
> cat repost-ads.py 

from pathlib import Path

from kijiji_bot import KijijiBot, KijijiBotException

ssid = "MTA******************************==;`"

ads_path = Path("ads")

is_using_alternate_ads = False
post_delay_seconds = 3600

try:
    bot = KijijiBot(ssid)
    bot.repost_ads(ads_path, is_using_alternate_ads, post_delay_seconds)
except KijijiBotException as exception:
    exception.dump()
    raise

**Comment by george-lim** [comment]
You are correct, adding a delay does not guarantee duplicate ad removal, it only increases the chance of doing it. Your best bet is using alternate ads + a combination of delay, and not reposting super frequently.

**Comment by Gary-0ak** [comment]
Acknowledged. Please take note that the delay is simply not working on my end.

**Comment by Gary-0ak** [comment]
Also, do you have an idea about how to make a "delete-only" script?

**Comment by Gary-0ak** [comment]
> I was able using Kijiji-Repost-Headless -s ssid.txt nuke

**Comment by george-lim** [comment]
> Acknowledged. Please take note that the delay is simply not working on my end.
Oh shoot, good call. The conditional is flipped for the delay. I'll have that fixed soon.
